version: "3"

services:
    redis:
        image: redis
        restart: always
        container_name: chat-redis
        ports:
            - ${REDIS_PORT}:6379
        networks:
            net:
    mongo:
        image: mongo
        restart: always
        container_name: chat-mongo
        ports:
            - ${MONGO_PORT}:27017
        networks:
            net:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    api:
        restart: unless-stopped
        container_name: chat-api
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
        ports:
            - 48334:${NODE_PORT}
        environment:
            - REDIS_HOST=172.18.0.1
            - MONGO_HOST=172.18.0.1
        networks:
            net:
    scylla:
        image: scylladb/scylla
        restart: unless-stopped
        container_name: chat-scylla-node1
        networks:
            - net

networks:
    net:
