version: "3"

services:
    redis:
        image: redis
        restart: always
        container_name: chat-redis
        ports:
            - 48379:6379
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - redis
        ports:
            - 48334:3443
