version: "3"

services:
    redis:
        image: redis
        restart: always
        container_name: chat-redis
        ports:
            - ${REDIS_PORT}:6379
        networks:
            net:
    api:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
        ports:
            - 48334:${NODE_PORT}
        environment:
            - REDIS_HOST=host.docker.internal
        networks:
            net:

networks:
    net:
